Convert requirements table to markdown
MicrosoftDocs/windows-driver-docs pull request #3171
Opened 2022-06-19 14:37 UTC by DJm00n

2022-06-22 00:10 UTC, jasonknichel requested changes

2022-06-22 00:10 UTC, jasonknichel commented on windows-driver-docs-pr/install/devpkey-device-basecontainerid.md
> +**Header**: Devpkey.h (include Devpkey.h)
Doesn't there need to be an empty line or something between these so they appear on separate lines?  The preview right now show them appearing on the same line (same applies to the other pages):
![image](https://user-images.githubusercontent.com/21045076/174916199-a024de26-5e21-453a-9578-e13145dc7653.png)

2022-06-23 19:32 UTC, barrygolden approved these changes

2022-06-23 19:33 UTC, merged

2022-06-23 19:34 UTC, barrygolden commented
@DJm00n, thanks for the PR!