Updated C30029
MicrosoftDocs/windows-driver-docs pull request #3188
Opened 2022-06-29 18:55 UTC by MugBergerFries

Added list of banned functions, standardized the formatting with my other PRs

2022-06-29 19:05 UTC, MichaelSquires requested changes

2022-06-29 19:05 UTC, MichaelSquires commented on windows-driver-docs-pr/devtest/30029-memory-allocating-function-requests-executable-memory.md
> +|```MM_PAGE_PRIORITY```| <ul><li>```POOL_NX_OPTIN_AUTO``` - This supports creating multiple binaries for different versions of Windows</li><li>```POOL_NX_OPTIN``` (+ ```ExInitializeDriverRuntime(DrvR
These first few rows (up through PAGE_EXECUTE_WRITECOPY) are actually flags, not functions. Can you make another table that accurately reflects that?

2022-06-29 19:47 UTC, MugBergerFries commented on windows-driver-docs-pr/devtest/30029-memory-allocating-function-requests-executable-memory.md
>  # C30029
Roger, I'll move to do so!

2022-07-21 17:58 UTC, Rastaban approved these changes

2022-07-21 18:13 UTC, MugBergerFries commented
@DOMARS This is ready to be merged!

2022-07-21 18:18 UTC, DOMARS approved these changes

2022-07-21 18:18 UTC, merged