preprod docs
MicrosoftDocs/windows-driver-docs pull request #3218
Opened 2022-08-01 23:09 UTC by Kevin-Tremblay

preproduction signing docs

2022-08-01 23:11 UTC, opbld32 commented
Docs Build status updates of commit _[a6d36b8](https://github.com/MicrosoftDocs/windows-driver-docs/commits/a6d36b8ee6fb477e73b28d3bb781ff56bd2f66d7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows-driver-docs-pr/dashboard/index.yml](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/index.yml) | :warning:Warning | | [Details](#user-content-31b01dd0ce22c9843977a7b9e97b8977-bdec2668)
[windows-driver-docs-pr/dashboard/manage-product-submissions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/manage-product-submissions.md) | :warning:Warning | | [Details](#user-content-fcc5fb2bb04f3a452c6939cede10987f-bdec2668)
[windows-driver-docs-pr/dashboard/managing-preprod-submissions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/managing-preprod-submissions.md) | :warning:Warning | | [Details](#user-content-715e8996402d471d1ef4591611097881-bdec2668)

<a id="31b01dd0ce22c9843977a7b9e97b8977-bdec2668"></a>
### [windows-driver-docs-pr/dashboard/index.yml](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/index.yml)
 - **Line 84, Column 13**: **[Warning: yaml-duplicate-key]** `````Key 'text' is already defined, remove the duplicate key.`````
 - **Line 85, Column 13**: **[Warning: yaml-duplicate-key]** `````Key 'url' is already defined, remove the duplicate key.`````

<a id="fcc5fb2bb04f3a452c6939cede10987f-bdec2668"></a>
### [windows-driver-docs-pr/dashboard/manage-product-submissions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/manage-product-submissions.md)
 - **Line 8, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Manage Product Submissions' is duplicated with other articles: 'dashboard/manage-product-submissions.md(8,1), dashboard/managing-preprod-submissions.md(6,1)'. First level headings must be unique within a docset.`````

<a id="715e8996402d471d1ef4591611097881-bdec2668"></a>
### [windows-driver-docs-pr/dashboard/managing-preprod-submissions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/managing-preprod-submissions.md)
 - **Line 2, Column 1**: **[Warning: ms-date-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-missing?branch=main)]** `````Missing required attribute: 'ms.date'. A freshness date is required for this content set. Add a date in format MM/DD/YYYY.`````
 - **Line 6, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Manage Product Submissions' is duplicated with other articles: 'dashboard/manage-product-submissions.md(8,1), dashboard/managing-preprod-submissions.md(6,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/bceeb04d-9c70-7649-b0f8-3c6e4c36710f/202208012309522956-3218/BuildReport?accessString=297e57badffb539d3c9af54408ef54f6f9414f55b138413829c603e84dbffcad).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/bceeb04d-9c70-7649-b0f8-3c6e4c36710f?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 15:35 UTC, anaharris-ms requested changes

2022-08-02 15:35 UTC, anaharris-ms commented on windows-driver-docs-pr/dashboard/index.yml
> +            text: Manage preproduction signing submissions
```suggestion
            - text: Manage preproduction signing submissions
```

2022-08-02 15:35 UTC, anaharris-ms commented on windows-driver-docs-pr/dashboard/managing-preprod-submissions.md
> +# Manage Product Submissions
```suggestion
# Manage Preprod Submissions
```

2022-08-03 23:47 UTC, tedhudek commented
@anaharris-ms I just came across https://docs.microsoft.com/en-us/windows-hardware/drivers/install/preproduction-driver-signing-and-install in a separate issue and thought I'd mention it here in case you want to link to it.

2022-08-04 21:20 UTC, opbld32 commented
Docs Build status updates of commit _[bef8542](https://github.com/MicrosoftDocs/windows-driver-docs/commits/bef8542cb76d6cc14bfa411a6c095db6203dc9dd)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows-driver-docs-pr/dashboard/index.yml](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/index.yml) | :x:Error | | [Details](#user-content-31b01dd0ce22c9843977a7b9e97b8977-bfa3f395)
[windows-driver-docs-pr/dashboard/manage-product-submissions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/manage-product-submissions.md) | :warning:Warning | | [Details](#user-content-fcc5fb2bb04f3a452c6939cede10987f-bfa3f395)
[windows-driver-docs-pr/dashboard/managing-preprod-submissions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/managing-preprod-submissions.md) | :warning:Warning | | [Details](#user-content-715e8996402d471d1ef4591611097881-bfa3f395)

<a id="31b01dd0ce22c9843977a7b9e97b8977-bfa3f395"></a>
### [windows-driver-docs-pr/dashboard/index.yml](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/index.yml)
 - **Line 84, Column 13**: **[Error: yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

<a id="fcc5fb2bb04f3a452c6939cede10987f-bfa3f395"></a>
### [windows-driver-docs-pr/dashboard/manage-product-submissions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/manage-product-submissions.md)
 - **Line 8, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Manage Product Submissions' is duplicated with other articles: 'dashboard/manage-product-submissions.md(8,1), dashboard/managing-preprod-submissions.md(6,1)'. First level headings must be unique within a docset.`````

<a id="715e8996402d471d1ef4591611097881-bfa3f395"></a>
### [windows-driver-docs-pr/dashboard/managing-preprod-submissions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/managing-preprod-submissions.md)
 - **Line 2, Column 1**: **[Warning: ms-date-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-missing?branch=main)]** `````Missing required attribute: 'ms.date'. A freshness date is required for this content set. Add a date in format MM/DD/YYYY.`````
 - **Line 6, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Manage Product Submissions' is duplicated with other articles: 'dashboard/manage-product-submissions.md(8,1), dashboard/managing-preprod-submissions.md(6,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/bceeb04d-9c70-7649-b0f8-3c6e4c36710f/202208042118019609-3218/BuildReport?accessString=c318a2b9f539a7d590f0ae0bbd2fdc463331aa6af47c45beeb879d5ae891266c).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/bceeb04d-9c70-7649-b0f8-3c6e4c36710f?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 21:22 UTC, opbld33 commented
Docs Build status updates of commit _[a96e9cc](https://github.com/MicrosoftDocs/windows-driver-docs/commits/a96e9cce1e30ad33c58f8aec55878126b0a2908a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows-driver-docs-pr/dashboard/index.yml](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/index.yml) | :x:Error | | [Details](#user-content-31b01dd0ce22c9843977a7b9e97b8977-cd53e6f3)
[windows-driver-docs-pr/dashboard/managing-preprod-submissions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/managing-preprod-submissions.md) | :warning:Warning | | [Details](#user-content-715e8996402d471d1ef4591611097881-cd53e6f3)

<a id="31b01dd0ce22c9843977a7b9e97b8977-cd53e6f3"></a>
### [windows-driver-docs-pr/dashboard/index.yml](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/index.yml)
 - **Line 84, Column 13**: **[Error: yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

<a id="715e8996402d471d1ef4591611097881-cd53e6f3"></a>
### [windows-driver-docs-pr/dashboard/managing-preprod-submissions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/managing-preprod-submissions.md)
 - **Line 2, Column 1**: **[Warning: ms-date-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-missing?branch=main)]** `````Missing required attribute: 'ms.date'. A freshness date is required for this content set. Add a date in format MM/DD/YYYY.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/bceeb04d-9c70-7649-b0f8-3c6e4c36710f/202208042119185271-3218/BuildReport?accessString=1714c36efdf49a84981d8b91a6be9e34e48b7fed94d7059833d07afaefbffd3b).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/bceeb04d-9c70-7649-b0f8-3c6e4c36710f?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 21:40 UTC, closed without merging

2022-08-04 21:42 UTC, opbld31 commented
Docs Build status updates of commit _[fb5453b](https://github.com/MicrosoftDocs/windows-driver-docs/commits/fb5453b0064afb2b826ded62e5840bca50d8075c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows-driver-docs-pr/dashboard/index.yml](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/index.yml) | :x:Error | | [Details](#user-content-31b01dd0ce22c9843977a7b9e97b8977-4dbc3942)
[windows-driver-docs-pr/dashboard/manage-preprod-submissions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/manage-preprod-submissions.md) | :warning:Warning | | [Details](#user-content-cb785e8efd339049bc36f092ef880d1e-4dbc3942)
[windows-driver-docs-pr/dashboard/managing-preprod-submissions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/managing-preprod-submissions.md) | :warning:Warning | | [Details](#user-content-715e8996402d471d1ef4591611097881-4dbc3942)

<a id="31b01dd0ce22c9843977a7b9e97b8977-4dbc3942"></a>
### [windows-driver-docs-pr/dashboard/index.yml](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/index.yml)
 - **Line 84, Column 13**: **[Error: yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

<a id="cb785e8efd339049bc36f092ef880d1e-4dbc3942"></a>
### [windows-driver-docs-pr/dashboard/manage-preprod-submissions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/manage-preprod-submissions.md)
 - **Line 1, Column 1**: **[Warning: ms-date-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-missing?branch=main)]** `````Missing required attribute: 'ms.date'. A freshness date is required for this content set. Add a date in format MM/DD/YYYY.`````
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 4, Column 1**: **[Warning: yaml-header-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 7, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Manage Preprod Submissions' is duplicated with other articles: 'dashboard/manage-preprod-submissions.md(7,1), dashboard/managing-preprod-submissions.md(6,1)'. First level headings must be unique within a docset.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="715e8996402d471d1ef4591611097881-4dbc3942"></a>
### [windows-driver-docs-pr/dashboard/managing-preprod-submissions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/managing-preprod-submissions.md)
 - **Line 2, Column 1**: **[Warning: ms-date-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-missing?branch=main)]** `````Missing required attribute: 'ms.date'. A freshness date is required for this content set. Add a date in format MM/DD/YYYY.`````
 - **Line 6, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Manage Preprod Submissions' is duplicated with other articles: 'dashboard/manage-preprod-submissions.md(7,1), dashboard/managing-preprod-submissions.md(6,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/bceeb04d-9c70-7649-b0f8-3c6e4c36710f/202208042140096122-3218/BuildReport?accessString=8585eb816cf43794b10475f1fe2ed70511d3f8d2b1fdcdc0f849121690b79d3b).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/bceeb04d-9c70-7649-b0f8-3c6e4c36710f?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 21:44 UTC, opbld32 commented
Docs Build status updates of commit _[fb5453b](https://github.com/MicrosoftDocs/windows-driver-docs/commits/fb5453b0064afb2b826ded62e5840bca50d8075c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[windows-driver-docs-pr/dashboard/index.yml](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/index.yml) | :x:Error | | [Details](#user-content-31b01dd0ce22c9843977a7b9e97b8977-bbb0b980)
[windows-driver-docs-pr/dashboard/manage-preprod-submissions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/manage-preprod-submissions.md) | :warning:Warning | | [Details](#user-content-cb785e8efd339049bc36f092ef880d1e-bbb0b980)
[windows-driver-docs-pr/dashboard/managing-preprod-submissions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/managing-preprod-submissions.md) | :warning:Warning | | [Details](#user-content-715e8996402d471d1ef4591611097881-bbb0b980)

<a id="31b01dd0ce22c9843977a7b9e97b8977-bbb0b980"></a>
### [windows-driver-docs-pr/dashboard/index.yml](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/index.yml)
 - **Line 84, Column 13**: **[Error: yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

<a id="cb785e8efd339049bc36f092ef880d1e-bbb0b980"></a>
### [windows-driver-docs-pr/dashboard/manage-preprod-submissions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/manage-preprod-submissions.md)
 - **Line 1, Column 1**: **[Warning: ms-date-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-missing?branch=main)]** `````Missing required attribute: 'ms.date'. A freshness date is required for this content set. Add a date in format MM/DD/YYYY.`````
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 4, Column 1**: **[Warning: yaml-header-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 7, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Manage Preprod Submissions' is duplicated with other articles: 'dashboard/manage-preprod-submissions.md(7,1), dashboard/managing-preprod-submissions.md(6,1)'. First level headings must be unique within a docset.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="715e8996402d471d1ef4591611097881-bbb0b980"></a>
### [windows-driver-docs-pr/dashboard/managing-preprod-submissions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/ketrem_preprod_docs/windows-driver-docs-pr/dashboard/managing-preprod-submissions.md)
 - **Line 2, Column 1**: **[Warning: ms-date-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-missing?branch=main)]** `````Missing required attribute: 'ms.date'. A freshness date is required for this content set. Add a date in format MM/DD/YYYY.`````
 - **Line 6, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Manage Preprod Submissions' is duplicated with other articles: 'dashboard/manage-preprod-submissions.md(7,1), dashboard/managing-preprod-submissions.md(6,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/bceeb04d-9c70-7649-b0f8-3c6e4c36710f/202208042140437802-3218/BuildReport?accessString=6ce9db38e108af1c4c6918161111d5c2fc0430764efd31a4c0d39eb80be27d57).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/bceeb04d-9c70-7649-b0f8-3c6e4c36710f?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>